FROM docker.io/golang:1.23.2-alpine AS build

WORKDIR /src

COPY ./lib/go/rpc ./lib/go/rpc
COPY ./lib/go/tempil ./lib/go/tempil
COPY ./hub ./hub
RUN go env -w GOCACHE=/go-cache
RUN go env -w GOMODCACHE=/gomod-cache
RUN --mount=type=cache,target=/gomod-cache --mount=type=cache,target=/go-cache \
    cd hub; CGO_ENABLED=0 GOOS=linux go build -o /app ./*.go

FROM gcr.io/distroless/static-debian12

WORKDIR /hub

COPY --from=build /app /app

EXPOSE 8080

ENTRYPOINT ["/app"]

